# Generated by Django 3.2.21 on 2023-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_auto_20231023_1543"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-id"], "verbose_name": "Tag"},
        ),
    ]
