# Generated by Django 3.2.21 on 2023-10-29 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("name",), "verbose_name": "Tag"},
        ),
    ]
